const allowedSkills = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Ruby",
  "PHP",
  "Perl",
  "Dart",
  "Scala",
  "Objective-C",
  "R",
  "MATLAB",
  "Lua",
  "HTML",
  "CSS",
  "SASS",
  "LESS",
  "Bootstrap",
  "Tailwind CSS",
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Gatsby",
  "jQuery",
  "WebAssembly",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "ASP.NET",
  "Ruby on Rails",
  "Laravel",
  "Symfony",
  "FastAPI",
  "NestJS",
  "GraphQL",
  "gRPC",
  "WebSockets",
  "Strapi",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "Redis",
  "Firebase",
  "DynamoDB",
  "Cassandra",
  "Neo4j",
  "Oracle DB",
  "MariaDB",
  "CockroachDB",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitHub Actions",
  "CI/CD",
  "Linux",
  "Bash Scripting",
  "PowerShell",
  "Nginx",
  "Apache",
  "Cloudflare",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Seaborn",
  "Scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Hugging Face",
  "OpenCV",
  "NLP",
  "Big Data",
  "Hadoop",
  "Spark",
  "Tableau",
  "Power BI",
  "Excel",
  "Penetration Testing",
  "Ethical Hacking",
  "Cryptography",
  "Network Security",
  "Firewalls",
  "Wireshark",
  "Metasploit",
  "Burp Suite",
  "SOC Analyst",
  "Threat Intelligence",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe XD",
  "Figma",
  "Sketch",
  "CorelDRAW",
  "GIMP",
  "Canva",
  "InVision",
  "Affinity Designer",
  "Blender (3D)",
  "Cinema 4D",
  "3ds Max",
  "ZBrush",
  "Adobe Premiere Pro",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Adobe After Effects",
  "Sony Vegas Pro",
  "HitFilm Express",
  "Camtasia",
  "VFX",
  "Motion Graphics",
  "Color Grading",
  "Adobe Audition",
  "FL Studio",
  "Ableton Live",
  "Logic Pro",
  "GarageBand",
  "Pro Tools",
  "Cubase",
  "Reaper",
  "Sound Design",
  "Mixing & Mastering",
  "SEO",
  "Content Writing",
  "Copywriting",
  "Social Media Marketing",
  "Google Ads",
  "Facebook Ads",
  "Email Marketing",
  "Affiliate Marketing",
  "Growth Hacking",
  "Blogging",
  "YouTube Management",
  "Unity",
  "Unreal Engine",
  "Godot",
  "Blender",
  "Game Physics",
  "Cocos2d",
  "OpenGL",
  "DirectX",
  "Chatbots",
  "AI Prompt Engineering",
  "RPA (Robotic Process Automation)",
  "ChatGPT API",
  "LangChain",
  "Stable Diffusion",
  "AutoML",
  "Reinforcement Learning",
  "Cisco Networking",
  "Network Administration",
  "Cloud Networking",
  "IT Support",
  "Active Directory",
  "VMware",
  "Virtualization",
  "Project Management",
  "Agile",
  "Scrum",
  "Kanban",
  "JIRA",
  "Trello",
  "Asana",
  "Business Analysis",
  "Microsoft Office",
  "Google Workspace",
  "Notion",
  "Blockchain",
  "Web3",
  "Smart Contracts",
  "Solidity",
  "Quantum Computing",
  "IoT",
  "3D Printing",
  "Video Editing",
  "Audio Editing",
  "Crafting",
  "Gaming",
  "Ninja hattori",
];

module.exports = allowedSkills;
